# Generated by Django 5.1.3 on 2024-11-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SteganographyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='steganography/originals/')),
                ('encoded_image', models.ImageField(blank=True, null=True, upload_to='steganography/encoded/')),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
