# Generated by Django 5.1.3 on 2024-11-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steganography", "0002_steganography_delete_steganographyimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="SteganographyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="steganography/images/")),
                (
                    "encoded_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="steganography/encoded_images/"
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Steganography",
        ),
    ]
